### ISSUE TITLE
NPE Crash

### ISSUE THREAD

**Issue by Sandriell** [tterrag1098/ColorblindHelper#1]
I added ColorBlindHelper and EnderCore and I am now getting this crash- works fine if I take them out. Incompatibility with Infernal Mobs?

Crash Log: https://gist.github.com/Sandriell/7672ec6c4abadc577285

Forge: 1448

**Comment by tterrag1098** [comment]
I have no idea what could cause this. Please report it to Infernal Mobs.

**Comment by Sandriell** [comment]
Updating Infernal Mobs fixed the issue.
