### ISSUE TITLE
items added to oredict with minetweaker don't work

### ISSUE THREAD

**Issue by RCXcrafter** [tterrag1098/ColorblindHelper#4]
When an item is aded to the oredictionary with minetweaker, it will not get the overlay from this mod applied to it. It's probably because minetweaker registers everything when the world is loaded and your mod decides what items shoud have what overlay when minecraft starts up.

**Comment by tterrag1098** [comment]
Minetweaker is doing its registrations far too late then, and I'm not pushing my checks _even later_ to get around it. Find another mod which actually does things properly...

**Comment by RCXcrafter** [comment]
The reason for that is so that the scripts can be reloaded ingame, but I'll use zzzzz customconfigs then, that one does work.

**Comment by tterrag1098** [comment]
Oredict should not be modified while ingame, that is a broken concept.
